- name: installing nginx
  hosts: ansible
  become: yes
  tasks:
  - ansible.builtin.package:
      name: nginx
      state: present
  - ansible.builtin.service:
      name: nginx
      enabled: yes
      state: restarted