- name: play level variables
  hosts: ansible
  vars:
    NAME: Datta
    ROLE: DevOps Engineer
    DOJ: 16-MAY-2022
  tasks:
  - name: printing the employee information
    ansible.builtin.debug:
     msg: My name is {{ NAME }}, working as {{ ROLE }}. I joined wipro on {{ DOJ }}.
 