- name: task level variables
  hosts: ansible
  vars:
    NAME: Datta
  tasks:
  - name: printing employee information
    vars:
       ROLE: DevOps Engineer
       DOJ: 16-MAY-2022
    ansible.builtin.debug:
       msg: My name is {{ NAME }}, working as {{ ROLE }}. I joined wipro on {{ DOJ }}.