- name: variable priority
  hosts: local
  connection: local
  vars: 
    DATA: "Data is from Playlevel"
  
  # vars_prompt: 
  # - name: DATA
  #   prompt: Please type Data is from Prompt
  #   private: false

  # vars_files:
  # - empinformation.yaml

  tasks:
  - name: print the name
    # vars:
    #   DATA: Data is from Task
    ansible.builtin.debug:
      msg: "This {{ DATA }}"


#Priority results:
# 1. Args
# 2. Task
# 3. File
# 4. Prompt
# 5. 