- name: data types in ansible
  hosts: local
  connection: local
  vars:
    Emp_Name: "Datta" #String
    age: 24 #Int / Number
    employee: true #Boolean (Ture or False)
    skills: #List - / []
    - Linux
    - GitHub
    - Shell Scripting
    - Ansible
    Traning_Details: #Map or Dictionary {}
      name: "DevOps"
      trainer: "SivaKumar"
      duration: 140

  tasks:
  - name: print the employee information
    ansible.builtin.debug:
     msg: |
      Employee_name: {{ Emp_Name }}
      Age: {{ age }}
      Employee: {{ employee }}
      Skills: {{ skills }}
      Details: {{ Traning_Details }}
